
appName: myhelmapp

port: 80

namespace: default

configmap:
  name: myhelmapp-configmap-v1
  data:
    msg: 'This app was deployed with helm!'

image:
  name: devopsjourney1/mywebapp
  tag: latest

